In [4]:
import dragonfly

a = dragonfly.geography.Position(0,0,0)


import numpy as np

a=np.array([3,3])

float(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [46]:
import numpy as np

a =np.array((1,1))

b=a.dtype
print(b)


np.issubdtype(b, np.number)

print(type(a.shape))

print(list(a.shape) in [[2],[3,1],[1,3]])

print(len((2,3)))





int32
<class 'tuple'>
True
2


In [3]:
from dragonfly.geography import Position, DCM_ECEF2NED
from dragonfly.utils import rotz
import numpy as np

lat = np.deg2rad(( 34. +  0./60 + 0.00174/3600)) # North
lon = np.deg2rad(-(117. + 20./60 + 0.84965/3600)) # West
alt = 251.702 # [meters]

aa= Position.fromLLA(lat,lon,alt)
print(aa.x,aa.y,aa.z)

print(DCM_ECEF2NED(lat,lon))

print(-np.cos(lon)*np.sin(lat))
print(-np.sin(lon))

print(rotz(np.pi/2)@np.array([1,0,0]))


-2430601.8276721514 -4702442.703100768 3546587.3582014046
[[ 0.25676467  0.4967581   0.82903757]
 [ 0.88834836 -0.45917011  0.        ]
 [ 0.38066927  0.73647416 -0.55919291]]
0.25676467171487716
0.8883483593780858
[ 0. -1.  0.]


In [4]:
print(float(0))

0.0


In [2]:
from dragonfly.geography import Position
import numpy as np

pos=[35,-12,1234]

aa = Position.fromLLA(np.deg2rad(pos[0]),np.deg2rad(pos[1]),pos[2])

print(aa.x)





5117118.20903842


In [6]:
class toto:
    def __init__(self,x=0,y=2):
        self.x=x
        self.y=y

a= [[toto(),toto()],[toto(),toto()]]

print(len(a))

2


In [ ]:
float([3,4])

In [2]:
# Program to handle multiple errors with one
# except statement
# Python 3

def fun(a):
	if a < 4:

		# throws ZeroDivisionError for a = 3
		b = a/(a-3)

	# throws NameError if a >= 4
	print("Value of b = ", b)
	
try:
	fun(3)
	fun(5)

# note that braces () are necessary here for
# multiple exceptions
except ZeroDivisionError:
	print("ZeroDivisionError Occurred and Handled")
except NameError:
	print("NameError Occurred and Handled")


ZeroDivisionError Occurred and Handled


In [13]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 3, 4, 5]

print(list1==list2)

True


In [1]:
from dragonfly.constant import EarthModel

aa = EarthModel("wgs84")

print(aa.model)
print(aa.a)

aa.model="wgs84"
print(aa.a)

print(aa.f)

print(aa.b)



WGS84
6378137.0
6378137.0
0.0033528106647474805
6356752.314245179


In [10]:
LLA4ECEF = [
    {"ECEF": [ 5117118.21, -1087677.05, 3638574.7 ],
    "LLA"  : [35,-12,1234]}, #lat lon alt
    {"ECEF": [ 1193872.96, 1584322.93, -6064737.91 ],
    "LLA"  : [-72,53,22135]}]

a= LLA4ECEF[0]["ECEF"]

[1,2,3]-[1,2,3]


TypeError: unsupported operand type(s) for -: 'list' and 'list'