In [2]:
import dragonfly.dev

a = dragonfly.dev.FileAnalysis("dragonfly\dev.py")
path = "dragonfly/"

# print(a)

# # print (a.fileFolder)
# # print(a.isValid())
# # print(a.commentsPercentage)
# # print(a.getInvalidItems())

# # print(a.getNumberInvalidItems())
# # print(a.getListInvalidItems())

# print(dragonfly.dev.FileAnalysis.MAX_MAINTENACE_LETTER)

# c = dragonfly.dev.FolderAnalysis(path)

# print(c.isValid())

#print(c)
print(a)






Code Metrics for dev.py:
	- Path: c:\Z\dragonFly\dragonfly
	- Maintenability: A (50.8)
	- Comment Percentage: 54.0 %
	- Complexity:
+-----------------------+--------------+-------------------+------+
|       Item Name       |    Class     | Complexity Letter | Line |
+-----------------------+--------------+-------------------+------+
|      _collectInfo     |     None     |       A (2)       | 508  |
|     chk_complexity    | CodeMetrics  |       A (1)       |  54  |
|    chk_maintenance    | CodeMetrics  |       A (1)       |  60  |
|      chk_comments     | CodeMetrics  |       A (1)       |  66  |
|     _verifyLetter     | CodeMetrics  |       A (3)       |  73  |
|      _verifyRange     | CodeMetrics  |       A (4)       |  83  |
|        __init__       | FileAnalysis |       A (3)       | 105  |
|        __str__        | FileAnalysis |       A (2)       | 126  |
|       complexity      | FileAnalysis |       A (3)       | 150  |
|        fileName       | FileAnalysis |       A (1)

In [11]:
# Python program showing a
# use of property() function
  
class Geeks:
     _toto =3
     def __init__(self,age):
          self._age = age
       
     # function to get value of _age
     def get_age(self):
         print("getter method called")
         return self._age
       
     # function to set value of _age
     def set_age(self, a):
         print("setter method called")

         self._age = a
  
     # function to delete _age attribute
     def del_age(self):
         del self._age
     
     age = property(get_age, set_age, del_age)
     

     def get_toto(self):
         print("getter method called")
         return self._age

     def set_toto(self,val):
        self._toto = val
        print("toto modification")

     def del_toto(self):
         del self._toto

     toto = property(get_toto, set_toto, del_toto)
  
mark = Geeks(20)

print(mark.age)
  
mark.age = 10
  
print(mark.age)

print(mark.toto)


getter method called
20
setter method called
getter method called
10
getter method called
10


In [14]:
VALID_RANGE = {"min":0, "max":100}
VALID_RANGE["min"]

0

In [2]:
from prettytable import PrettyTable
my_table = PrettyTable()
my_table.add_row([1, "Bob", 6, 11])
my_table.add_row([2, "Freddy", 4, 10])
my_table.add_row([3, "John", 7, 13])
print(my_table)

+---------+---------+---------+---------+
| Field 1 | Field 2 | Field 3 | Field 4 |
+---------+---------+---------+---------+
|    1    |   Bob   |    6    |    11   |
|    2    |  Freddy |    4    |    10   |
|    3    |   John  |    7    |    13   |
+---------+---------+---------+---------+


In [25]:
import os
import pathlib

listFiles2test = [""]

for path, subdirs, files in os.walk('dragonfly'):
    for name in files:
        fileExtension = pathlib.Path(name).suffix
        if fileExtension ==".py" and name != "__init__.py":
            listFiles2test= listFiles2test.append(os.path.join(path, name))

print(listFiles2test)
        

AttributeError: 'NoneType' object has no attribute 'append'

In [111]:
import dragonfly.utils

class testClass(dragonfly.utils.immutableClass):
    def __init__(self,x,y):
        self.x = x
        self.y = y

        # initialize parent class "SlotsFreezer"
        super().__init__()


a = testClass(3,4)

a.x = 3







AttributeError: This object is frozen!

In [2]:
from dragonfly.dev import FileAnalysis, FolderAnalysis

path = 'c:\\Z\\dragonFly\\dragonfly\\constant.py'

a = FileAnalysis(path)

tt = a.complexity

#print(tt)

path = os. getcwd()

b = FolderAnalysis(path)

print(b.commentPercentage)


[['c:\\Z\\dragonFly\\dragonfly\\constant.py', 12.1], ['c:\\Z\\dragonFly\\dragonfly\\dev.py', 34.9], ['c:\\Z\\dragonFly\\dragonfly\\geography.py', 47.1], ['c:\\Z\\dragonFly\\dragonfly\\gravity.py', 59.5], ['c:\\Z\\dragonFly\\dragonfly\\utils.py', 42.9]]


In [1]:
from dragonfly.gravity import Gravity
from dragonfly.geography import Position
from dragonfly.constant import EarthModel
import numpy as np

pos = Position.fromLLA(np.deg2rad(90),0,0)

g = Gravity(pos.x,pos.y,pos.z).toNumpy()

print(g)

ee = EarthModel()

print((ee.mu/ee.a**2)*(1+3/2*ee.j2))


print((ee.mu/ee.b**2)*(1+3/2*ee.j2*(ee.a/ee.b)**2*-2))



[[-6.04109601e-16]
 [-0.00000000e+00]
 [-9.83206684e+00]]
9.814197355899799
9.83206684120325


In [3]:
from dragonfly.geography import Position, DCM_ECEF2NED
from dragonfly.utils import rotz
import numpy as np

lat = np.deg2rad(( 34. +  0./60 + 0.00174/3600)) # North
lon = np.deg2rad(-(117. + 20./60 + 0.84965/3600)) # West
alt = 251.702 # [meters]

aa= Position.fromLLA(lat,lon,alt)
print(aa.x,aa.y,aa.z)

print(DCM_ECEF2NED(lat,lon))

print(-np.cos(lon)*np.sin(lat))
print(-np.sin(lon))

print(rotz(np.pi/2)@np.array([1,0,0]))


-2430601.8276721514 -4702442.703100768 3546587.3582014046
[[ 0.25676467  0.4967581   0.82903757]
 [ 0.88834836 -0.45917011  0.        ]
 [ 0.38066927  0.73647416 -0.55919291]]
0.25676467171487716
0.8883483593780858
[ 0. -1.  0.]


In [4]:
print(float(0))

0.0


In [4]:
from dragonfly.geography import Position
import numpy as np

pos = Position.fromLLA(0,0,0)

lat,lon, alt = pos.toLLA()

print(pos)

str(Position(0,0,0))



ECEF Coordinates:
x : 6378137.0
y : 0.0
z : 0.0


'ECEF Coordinates:\nx : 0.0\ny : 0.0\nz : 0.0'

In [6]:
class toto:
    def __init__(self,x=0,y=2):
        self.x=x
        self.y=y

a= [[toto(),toto()],[toto(),toto()]]

print(len(a))

2


In [1]:
print(range(3.4))

TypeError: 'float' object cannot be interpreted as an integer

In [2]:
# Program to handle multiple errors with one
# except statement
# Python 3

def fun(a):
	if a < 4:

		# throws ZeroDivisionError for a = 3
		b = a/(a-3)

	# throws NameError if a >= 4
	print("Value of b = ", b)
	
try:
	fun(3)
	fun(5)

# note that braces () are necessary here for
# multiple exceptions
except ZeroDivisionError:
	print("ZeroDivisionError Occurred and Handled")
except NameError:
	print("NameError Occurred and Handled")


ZeroDivisionError Occurred and Handled


In [13]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 3, 4, 5]

print(list1==list2)

True


In [1]:
from dragonfly.constant import EarthModel

aa = EarthModel("wgs84")

print(aa.model)
print(aa.a)

aa.model="wgs84"
print(aa.a)

print(aa.f)

print(aa.b)



WGS84
6378137.0
6378137.0
0.0033528106647474805
6356752.314245179


In [10]:
LLA4ECEF = [
    {"ECEF": [ 5117118.21, -1087677.05, 3638574.7 ],
    "LLA"  : [35,-12,1234]}, #lat lon alt
    {"ECEF": [ 1193872.96, 1584322.93, -6064737.91 ],
    "LLA"  : [-72,53,22135]}]

a= LLA4ECEF[0]["ECEF"]

[1,2,3]-[1,2,3]


TypeError: unsupported operand type(s) for -: 'list' and 'list'