In [46]:
import radon.visitors
import radon.metrics

with open('dragonfly/geography.py', 'r') as file:
    data = file.read()

from radon.visitors import ComplexityVisitor

v = ComplexityVisitor.from_code(data)

a=v.functions
print(type(a[1]))
print(a)
b= a[0]
print(b.complexity)






<class 'radon.visitors.Function'>
[Function(name='DCM_ECI2ECEF', lineno=242, col_offset=0, endline=262, is_method=False, classname=None, closures=[], complexity=1), Function(name='dcm_ecef2ned', lineno=265, col_offset=0, endline=280, is_method=False, classname=None, closures=[], complexity=1), Function(name='dcm_ecef2enu', lineno=283, col_offset=0, endline=300, is_method=False, classname=None, closures=[], complexity=1), Function(name='angle2dcm', lineno=304, col_offset=0, endline=326, is_method=False, classname=None, closures=[], complexity=2), Function(name='dcm2angle', lineno=329, col_offset=0, endline=368, is_method=False, classname=None, closures=[], complexity=2), Function(name='getRange', lineno=371, col_offset=0, endline=456, is_method=False, classname=None, closures=[], complexity=11)]
DCM_ECI2ECEF


In [25]:
import os
import pathlib

listFiles2test = [""]

for path, subdirs, files in os.walk('dragonfly'):
    for name in files:
        fileExtension = pathlib.Path(name).suffix
        if fileExtension ==".py" and name != "__init__.py":
            listFiles2test= listFiles2test.append(os.path.join(path, name))

print(listFiles2test)
        

AttributeError: 'NoneType' object has no attribute 'append'

In [69]:
import os
import radon.visitors
import radon.metrics
from radon.visitors import ComplexityVisitor

path = os. getcwd()

pythonFiles = [os.path.join(root, name)
             for root, dirs, files in os.walk(path)
             for name in files
             if (name.endswith((".py")) and # only python files
                 name !="__init__.py" and # remove the module initialisation 
                 not("test" in name.lower()) # remove test file
                 )]

#test namedtuple
from collections import namedtuple

CodeMetrics = namedtuple("CodeMetrics",["path","name","CyclomaticComplexity"])

result = []

# analyse file
for pythonFile in pythonFiles:
    with open(pythonFile, 'r') as file:
        data = file.read()

    res = ComplexityVisitor.from_code(data).functions

    for item in res :
        result.append(CodeMetrics(pythonFile,item.name,item.complexity))


# see https://realpython.com/python-namedtuple/   

import radon.complexity

print(radon.complexity.cc_rank(11))
    
import radon.metrics

tt = radon.metrics.h_visit(data)

print(tt.functions)



C
[('_assertInstance', HalsteadReport(h1=1, h2=1, N1=1, N2=1, vocabulary=2, length=2, calculated_length=0.0, volume=2.0, difficulty=0.5, effort=1.0, time=0.05555555555555555, bugs=0.0006666666666666666)), ('rotx', HalsteadReport(h1=0, h2=0, N1=0, N2=0, vocabulary=0, length=0, calculated_length=0, volume=0, difficulty=0, effort=0, time=0.0, bugs=0.0)), ('roty', HalsteadReport(h1=0, h2=0, N1=0, N2=0, vocabulary=0, length=0, calculated_length=0, volume=0, difficulty=0, effort=0, time=0.0, bugs=0.0)), ('rotz', HalsteadReport(h1=0, h2=0, N1=0, N2=0, vocabulary=0, length=0, calculated_length=0, volume=0, difficulty=0, effort=0, time=0.0, bugs=0.0)), ('__fundamentalRotation', HalsteadReport(h1=1, h2=2, N1=1, N2=2, vocabulary=3, length=3, calculated_length=2.0, volume=4.754887502163469, difficulty=0.5, effort=2.3774437510817346, time=0.1320802083934297, bugs=0.0015849625007211565)), ('__input_check_3x1', HalsteadReport(h1=4, h2=10, N1=6, N2=11, vocabulary=14, length=17, calculated_length=41.21

In [1]:
from dragonfly.utils import input_check_3x3
import numpy as np
value = np.ndarray((2,2))
print(input_check_3x3(value))

The input shall a [3x3] numpy array
Current Value    : [[6.9525323e-310 0.0000000e+000]
 [0.0000000e+000 1.4326314e-311]]
Curent Data Type : <class 'numpy.ndarray'>
[[6.9525323e-310 0.0000000e+000]
 [0.0000000e+000 1.4326314e-311]]
None


In [2]:
from dragonfly.gravity import Gravity
from dragonfly.geography import Position
from dragonfly.constant import EarthModel
import numpy as np

pos = Position.fromLLA(np.deg2rad(90),0,0)

g = Gravity(pos.x,pos.y,pos.z).toNumpy()

print(g)

ee = EarthModel()

print((ee.mu/ee.a**2)*(1+3/2*ee.j2))


print((ee.mu/ee.b**2)*(1+3/2*ee.j2*(ee.a/ee.b)**2*-2))



[[-6.04109601e-16]
 [-0.00000000e+00]
 [-9.83206684e+00]]
9.814197355899799
9.83206684120325


In [3]:
from dragonfly.geography import Position, DCM_ECEF2NED
from dragonfly.utils import rotz
import numpy as np

lat = np.deg2rad(( 34. +  0./60 + 0.00174/3600)) # North
lon = np.deg2rad(-(117. + 20./60 + 0.84965/3600)) # West
alt = 251.702 # [meters]

aa= Position.fromLLA(lat,lon,alt)
print(aa.x,aa.y,aa.z)

print(DCM_ECEF2NED(lat,lon))

print(-np.cos(lon)*np.sin(lat))
print(-np.sin(lon))

print(rotz(np.pi/2)@np.array([1,0,0]))


-2430601.8276721514 -4702442.703100768 3546587.3582014046
[[ 0.25676467  0.4967581   0.82903757]
 [ 0.88834836 -0.45917011  0.        ]
 [ 0.38066927  0.73647416 -0.55919291]]
0.25676467171487716
0.8883483593780858
[ 0. -1.  0.]


In [4]:
print(float(0))

0.0


In [4]:
from dragonfly.geography import Position
import numpy as np

pos = Position.fromLLA(0,0,0)

lat,lon, alt = pos.toLLA()

print(pos)

str(Position(0,0,0))



ECEF Coordinates:
x : 6378137.0
y : 0.0
z : 0.0


'ECEF Coordinates:\nx : 0.0\ny : 0.0\nz : 0.0'

In [6]:
class toto:
    def __init__(self,x=0,y=2):
        self.x=x
        self.y=y

a= [[toto(),toto()],[toto(),toto()]]

print(len(a))

2


In [1]:
print(range(3.4))

TypeError: 'float' object cannot be interpreted as an integer

In [2]:
# Program to handle multiple errors with one
# except statement
# Python 3

def fun(a):
	if a < 4:

		# throws ZeroDivisionError for a = 3
		b = a/(a-3)

	# throws NameError if a >= 4
	print("Value of b = ", b)
	
try:
	fun(3)
	fun(5)

# note that braces () are necessary here for
# multiple exceptions
except ZeroDivisionError:
	print("ZeroDivisionError Occurred and Handled")
except NameError:
	print("NameError Occurred and Handled")


ZeroDivisionError Occurred and Handled


In [13]:
list1 = [1, 2, 3, 4, 5]
list2 = [1, 2, 3, 4, 5]

print(list1==list2)

True


In [1]:
from dragonfly.constant import EarthModel

aa = EarthModel("wgs84")

print(aa.model)
print(aa.a)

aa.model="wgs84"
print(aa.a)

print(aa.f)

print(aa.b)



WGS84
6378137.0
6378137.0
0.0033528106647474805
6356752.314245179


In [10]:
LLA4ECEF = [
    {"ECEF": [ 5117118.21, -1087677.05, 3638574.7 ],
    "LLA"  : [35,-12,1234]}, #lat lon alt
    {"ECEF": [ 1193872.96, 1584322.93, -6064737.91 ],
    "LLA"  : [-72,53,22135]}]

a= LLA4ECEF[0]["ECEF"]

[1,2,3]-[1,2,3]


TypeError: unsupported operand type(s) for -: 'list' and 'list'