# Evaluate linear algrebra with NUMPY

In [1]:
import numpy as np

## Define Value

In [13]:
#define the array
x = np.array([1,2,3])
print(f"x = {x} size : {x.shape}")

#define matrix
M = np.matrix([[1, 2,3], [4,5,6],[7,8,9]])
print(f"M =\n {M}")


x = [1 2 3] size : (3,)
M =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Vector Size

In [19]:
y = x[:,None]
print(f"y = {y}")

y = [[1]
 [2]
 [3]]


## matrix product

In [20]:
RES = M@(x.T)

print(f"RES =\n {RES} \n size : {RES.shape}")
RES = M@y

print(f"RES =\n {RES} \n size : {RES.shape}")

RES =
 [[14 32 50]] 
 size : (1, 3)
RES =
 [[14]
 [32]
 [50]] 
 size : (3, 1)
